### ISSUE TITLE
HW3 dgemm include path

### ISSUE THREAD

**Issue by adkevin3307** [yungyuc/nsdhw_21sp#28]
Hi,

In the homework 3, we need to use `dgemm` in `multiply_mkl` function.
And we need to include `mkl` in our `Makefile`, so I want to make sure the correct path for `mkl`.

Thanks.

**Comment by yungyuc** [comment]
@adkevin3307 For the MKL path in the nsd aws image, please see https://github.com/yungyuc/nsd/blob/master/contrib/install.sh .  For the path in GitHub Action, see https://github.com/yungyuc/nsdhw_21sp/blob/master/.github/workflows/hw3.yml .
