### ISSUE TITLE
HW3 speed compare

### ISSUE THREAD

**Issue by adkevin3307** [yungyuc/nsdhw_21sp#29]
Hi,

> The tiling version must be 20% faster than the naive version (runtime must be less than 80%).

In the homework 3 spec, our `multiply_tile` will be compared w/ naive version.
But in `validate.py`, function `check_tile` looks like it compare tiling version and mkl version.
Is this a typo or tiling version faster than mkl version is easier?

Thanks.

**Comment by yungyuc** [comment]
It is correct that `check_tile()` calculate the ratio of the time between the tiled version and MKL.  But the check of speed-up uses time ratio to MKL between tiled and non-tiled (tile set to 0) versions, see https://github.com/yungyuc/nsdhw_21sp/blob/master/hw3/validate.py#L183 .

(Please reopen the ticket if you still have questions on this.)
