### ISSUE TITLE
[hw3] Question about performance.txt

### ISSUE THREAD

**Issue by Xi-Plus** [yungyuc/nsdhw_21sp#31]
1. <s>Do I need to include `performance.txt` in the PR?</s>
2. Does the code to generate `performance.txt` to be placed in unit tests or separate script?

**Comment by Xi-Plus** [comment]
I got the answer of first question at [README](https://github.com/yungyuc/nsdhw_21sp/blob/hw3/hw3/README.rst#submission).

**Comment by yungyuc** [comment]
Thanks.

**Comment by Xi-Plus** [comment]
@yungyuc I want to know the answer of second question.

**Comment by yungyuc** [comment]
It doesn't matter.  As long as the `validate.py` script can generate the text file, it's fine.
